//
// Created by alex scalese on 2019-02-13.
//

#ifndef MUSICPLAYER_STATE_EXAMPLE_MUSICPLAYER_HPP
#define MUSICPLAYER_STATE_EXAMPLE_MUSICPLAYER_HPP


class MusicPlayer {

};


#endif //MUSICPLAYER_STATE_EXAMPLE_MUSICPLAYER_HPP
